// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtSvbrasYimpB_HPizeNsmnrArlsjBdzw',
    appId: '1:503774546058:web:2bc307606a95cb337ac573',
    messagingSenderId: '503774546058',
    projectId: 'milesassignement',
    authDomain: 'milesassignement.firebaseapp.com',
    storageBucket: 'milesassignement.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3VSMnp4CyqUQhZlQamMWZoP326icJMMs',
    appId: '1:503774546058:android:07af0d5608aa91837ac573',
    messagingSenderId: '503774546058',
    projectId: 'milesassignement',
    storageBucket: 'milesassignement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdx5OEXgrGIqZTZ6WFgLWMHQ2WXIqY0aw',
    appId: '1:503774546058:ios:4dae3a54831603607ac573',
    messagingSenderId: '503774546058',
    projectId: 'milesassignement',
    storageBucket: 'milesassignement.firebasestorage.app',
    iosBundleId: 'com.example.milesAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdx5OEXgrGIqZTZ6WFgLWMHQ2WXIqY0aw',
    appId: '1:503774546058:ios:4dae3a54831603607ac573',
    messagingSenderId: '503774546058',
    projectId: 'milesassignement',
    storageBucket: 'milesassignement.firebasestorage.app',
    iosBundleId: 'com.example.milesAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtSvbrasYimpB_HPizeNsmnrArlsjBdzw',
    appId: '1:503774546058:web:4aab2d24e98f22db7ac573',
    messagingSenderId: '503774546058',
    projectId: 'milesassignement',
    authDomain: 'milesassignement.firebaseapp.com',
    storageBucket: 'milesassignement.firebasestorage.app',
  );
}
